<?php

/**
 * @file
 * Contains field_visibility.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function field_visibility_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the field_visibility module.
    case 'help.page.field_visibility':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a UI for editing role level visibility of fields in Node edit forms.') . '</p>';
      return $output;

    default:
  }
}
