#!/usr/bin/env bash

## Run Code Sniffer on all files
##
## Usage: fin code-sniff
##
## Applies automatic fixes to files using Drupal standards.
##
## Includes extensions:	php, module, inc, install, test, profile, theme
## Ignores:		features.*, *.pages*.inc

fin blt tests:phpcs:sniff:all
